<?php
    include('DBConnection.php');

    try {
        $sql = new DBConnection("compcreator");
        $sql->query("DROP DATABASE IF EXISTS CompCreator;");
        $sql->query("CREATE DATABASE CompCreator CHARACTER SET utf8 COLLATE utf8_unicode_ci;");
        $sql->query("USE CompCreator;");
        $sql->query("DROP TABLE IF EXISTS CPU;");
        $sql->query("DROP TABLE IF EXISTS GPU;");
        $sql->query("DROP TABLE IF EXISTS SystemCase;");
        $sql->query("DROP TABLE IF EXISTS PSU;");
        $sql->query("DROP TABLE IF EXISTS StorageDrive;");
        $sql->query("DROP TABLE IF EXISTS Memory;");
        $sql->query("DROP TABLE IF EXISTS MotherBoard;");
        $sql->query("DROP TABLE IF EXISTS Component;");

		$sql->query("CREATE TABLE Component(
			CompID INT(10) PRIMARY KEY NOT NULL,
			CompName VARCHAR(100) NOT NULL,
			CompPrice DECIMAL(6,2) NOT NULL,
			CompLink VARCHAR(200) NOT NULL,
            CompDate  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP());
        ");

		$sql->query("CREATE TABLE CPU(
			CompID INT (10)PRIMARY KEY NOT NULL,
			ClockFrequency DECIMAL(10,2),
			ProductPage VARCHAR(200),
			L3Cache DECIMAL(10,2),
			TurboBoostCore VARCHAR(100),
			CPUType VARCHAR(100),
			BoxVersion VARCHAR(100),
            Boxed VARCHAR(100),
            ECC VARCHAR(100),
            TechnologyType VARCHAR(100),
			NumberOfThreads INT(8),
            Instructions VARCHAR(100),
            Manual VARCHAR(100),
			64bitProcessor VARCHAR(100),
            Busspeed INT(8),
            TubroFrequency INT(8),
			L2Cache DECIMAL(10,2),
			Socket VARCHAR(100),
			NumberOfCores INT(8),
            CPUthrottling VARCHAR(100),
			GraphicsProcessor VARCHAR(100),
			ReleaseYear INT(8),
			ThermalDesignPower INT(8),
			IntegratedGraphics VARCHAR(100),
			Virtualization VARCHAR(100),
            MicronTechnology VARCHAR(100),
            Frequency INT(100),
            MaxFrequency INT(100),
            Dimensions VARCHAR(100),
            Otherconnectors VARCHAR(100),
			CPURating INT (10) NOT NULL DEFAULT '99999999',
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE );
        ");

		$sql->query("CREATE TABLE GPU(
            CompID INT (10)PRIMARY KEY NOT NULL,
			Cooling VARCHAR(100),
			NumberOfFans INT(8),
			SemiPassive VARCHAR(100),
			FactoryOverclocked VARCHAR(100),
			GraphicsProcessor VARCHAR(100),
			LowProfile VARCHAR(100),
			NonreferenceCooler VARCHAR(100),
			PCIExpressVersion VARCHAR(100),
			Displayport VARCHAR(100),
			NumberOfDisplayportoutputs INT(8),
			DVI VARCHAR(100),
			NumberOfDVIOutputs INT(8),
			HDMI VARCHAR(100),
			NumberOfHdmiOutputs INT(8),
			VGAOutputs VARCHAR(100),
			MaximumResolution VARCHAR(100),
			NumberOfSupportedMonitors INT(8),
			Length INT(8),
			NumberOfSlots INT(8),
			DirectX DECIMAL(10,2),
			HDR VARCHAR(100),
			OpenGL DECIMAL(10,2),
			Vulkan DECIMAL(10,2),
			SupportForMultipleGraphicsCards VARCHAR(100),
			MemoryBandwidth DECIMAL(10,2),
			MemoryCapacity DECIMAL(10,2),
			MemoryInterface DECIMAL(10,2),
			MemorySpeed DECIMAL(10,2),
			MemoryType VARCHAR(100),
			GPUBoost VARCHAR(100),
			ProcessorSpeed DECIMAL(10,2),
			SupplementaryPowerConnector VARCHAR(100),
			ManufacturerWarranty INT(8),
			ReleaseYear INT(8),
			ProductPage VARCHAR(200),
            Otherconnectors VARCHAR(100),
            PCIExpresschannels INT(8),
            UnifiedShadingarchitecture VARCHAR(100),
            UnifiedShaders INT(8),
            CADCAMGraphicsCard VARCHAR(100),
            DualLink VARCHAR(100),
            SingleLink VARCHAR(100),
            DVIHDMIadapterincluded VARCHAR(100),
            HDMIDVIadapterincluded VARCHAR(100),
            DVIVGAadapterincluded VARCHAR(100),
            HDMIversion DECIMAL(8,2),
            TypeofHDMIconnector VARCHAR(100),
            DisplayPortversion DECIMAL(8,2),
            TypeofDisplayPortconnector VARCHAR(100),
            Operatingsystem VARCHAR(100),
            Features VARCHAR(100),
            Memoryacceleration VARCHAR(100),
            MultiGPUTechnology VARCHAR(100),
            Dimensions VARCHAR(100),
            Fibre VARCHAR(100),
			GPURating INT (10) NOT NULL DEFAULT '99999999',
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

		$sql->query("CREATE TABLE SystemCase(
			CompID INT (10)PRIMARY KEY NOT NULL,
            Material VARCHAR(100),
            Dimensions VARCHAR(100),
            No VARCHAR(100),
            FanSpaces220230mm INT(8),
            ProductPage VARCHAR(200),
            NumberOfCardSlots INT(8),
            35DriveBays INT(8),
            FanSpaces120mm INT(8),
            ScrewlessDesign VARCHAR(100),
            FanSpaces9092mm INT(8),
            FanSpaces400mm INT(8),
            FanSpaces4050mm INT(8),
            HeatZones INT(8),
            Format VARCHAR(100),
            FanSpaces180190mm INT(8),
            PSUIncluded VARCHAR(100),
            FanSpaces6070mm INT(8),
            PositionOfThePowerSupply INT(8),
            Volume VARCHAR(100),
            FanSpaces100mm INT(8),
            SupportedMotherboards VARCHAR(100),
            FanSpaces330mm INT(8),
            FanSpaces140mm INT(8),
            Fanspaces200mm INT(8),
            BuiltinWatercooling VARCHAR(100),
            FanSpaces80mm INT(8),
            Colour VARCHAR(100),
            Manual VARCHAR(100),
            RoomForExpansion VARCHAR(100),
            SlimDiskStation VARCHAR(100),
            ReleaseYear INT(8),
            MaximumLengthOfVideoCard INT(8),
            HeightOfExpansionSlots INT(8),
            ActiveCooling VARCHAR(100),
            Features VARCHAR(100),
            525DriveBays INT(8),
            Weight INT(8),
            WaterCooling VARCHAR(100),
            FanSpacesTotal INT(8),
            SlimOpticalDrive VARCHAR(100),
            MaximumMotherboardSize VARCHAR(100),
            25DriveBays INT(8),
            MaxCPUCoolerHeight INT(8),
            FanSpaces250mm INT(8),
            TypeOfChassis VARCHAR(100),
            FrontConnections VARCHAR(100),
            BuiltInMicrophone VARCHAR(100),
            PictBridge VARCHAR(100),
            GPRS VARCHAR(100),
            OtherConnectors VARCHAR(100),
            PaperStorage VARCHAR(100),
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

		$sql->query("CREATE TABLE PSU(
			CompID INT (10)PRIMARY KEY NOT NULL,
            Capacity INT(8),
            Dimensions VARCHAR(100),
            PowerConnectionsForThe35 VARCHAR(100),
            ProductPage VARCHAR(200),
            80PlusCertification VARCHAR(100),
            FanConnection VARCHAR(100),
            ATX12V VARCHAR(100),
            FanSize INT(8),
            Modular VARCHAR(100),
            Number12VLines INT(8),
            CableSocks VARCHAR(100),
            ATX VARCHAR(100),
            PowerConnectorsForSATA VARCHAR(100),
            Current12V8 INT(8),
            Current12V7 INT(8),
            Current12V6 INT(8),
            Current12V5 INT(8),
            Current12V4 INT(8),
            Current12V3 INT(8),
            Current12V2 INT(8),
            Current12V1 INT(8),
            Efficiency INT(8),
            ManufacturerWarranty VARCHAR(100),
            PowerSupplyUnitPSU VARCHAR(100),
            SemiPassive VARCHAR(100),
            TemperatureControlledFan VARCHAR(100),
            Current5Vsb INT(8),
            Manual VARCHAR(100),
            NumberOfFans VARCHAR(100),
            Current5V INT(8),
            Current12V INT(8),
            ReleaseYear INT(8),
            Current33V INT(8),
            PowerConnectionsForTheFloppyDrive VARCHAR(100),
            ActiveCooling VARCHAR(100),
            Features VARCHAR(100),
            Format VARCHAR(100),
            BearingType VARCHAR(100),
            Version VARCHAR(100),
            EPS12V VARCHAR(100),
            PowerConnectionsForPCIExpress VARCHAR(100),
            TotalAmperage12V INT(8),
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

		$sql->query("CREATE TABLE SSD(
			CompID INT (10)PRIMARY KEY NOT NULL,
			MaximumReadSpeed INT(8),
			ControllerChip VARCHAR(100),
			PriceGB DECIMAL(10,2),
			ManufacturerWarranty INT(8),
			Interface VARCHAR(100),
			FormFactor VARCHAR(100),
			TypeOfFlashMemory VARCHAR(100),
			Connection VARCHAR(100),
			ProductPage VARCHAR(200),
			Weight VARCHAR(100),
			MaximumWriteSpeed INT(8),
            4KBRandomRead VARCHAR(100),
            Dimensions VARCHAR(100),
            4KBRandomWrite VARCHAR(100),
            Cachesize INT(8),
            Cachememory VARCHAR(100),
            Powerconsumption INT(8),
            OperationalPowerConsumption INT(8),
            TBW VARCHAR(100),
            Hybriddisk VARCHAR(100),
            Manual VARCHAR(100),
            Internalconnection VARCHAR(100),
            Externalconnection VARCHAR(100),
            Features VARCHAR(100),
            M2formfactor VARCHAR(100),
            Firewire VARCHAR(100),
			Size INT(8),
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

		$sql->query("CREATE TABLE HDD(
			CompID INT (10)PRIMARY KEY NOT NULL,
			InternalTransferRate INT(8),
			ProductPage VARCHAR(200),
			HybridDisk VARCHAR(100),
			PriceTB DECIMAL(10,2),
			FormFactor VARCHAR(100),
			ManufacturerWarranty INT(8),
			Interface VARCHAR(100),
			CacheSize INT(8),
			Connection VARCHAR(100),
			ReleaseYear INT(8),
			RotationalSpeed VARCHAR(100),
			NoiseLevel VARCHAR(100),
			HardDriveSize DECIMAL(10,2),
            Dimensions VARCHAR(100),
            MeanTimeBetweenFailure VARCHAR(100),
            Averagesearch  VARCHAR(100),
            UnrecoverableReadError VARCHAR(100),
            Numberofdisks INT(8),
            Manual VARCHAR(100),
            Features VARCHAR(100),
            AdvancedFormat VARCHAR(100),
            OperationalPowerConsumption INT(8),
            Powerconsumption INT(8),
            FlashMemory VARCHAR(100),
            Fibre VARCHAR(100),
            GPRS VARCHAR(100),
            USB VARCHAR(100),
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

		$sql->query("CREATE TABLE Memory(
			CompID INT (10)PRIMARY KEY NOT NULL,
			NumberOfModules INT(8),
			MemorySpeed VARCHAR(100),
			MemoryCapacity INT(8),
			ECC VARCHAR(100),
			ReleaseYear INT(8),
			PriceGB DECIMAL(10,2),
			ManufacturerWarranty VARCHAR(100),
			MemoryCapacityPerModule INT(8),
			CASLatency INT(8),
			TypeOfMemory VARCHAR(100),
			ProductPage VARCHAR(200),
			Voltage VARCHAR(100),
            Features VARCHAR(100),
            Registered VARCHAR(100),
            Cooling VARCHAR(100),
            IntelXMP VARCHAR(100),
            Timing VARCHAR(100),
            Manual VARCHAR(100),
            Paperstorage VARCHAR(100),
            Weight INT(8),
            Capacity INT(8),
            M2key VARCHAR(100),
            USBversion VARCHAR(100),
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

		$sql->query("CREATE TABLE MotherBoard(
			CompID INT (10)PRIMARY KEY NOT NULL,
            InternalSerialPort VARCHAR(100),
            CompositeOutput VARCHAR(100),
            InternalThunderbolt VARCHAR(100),
            Width VARCHAR(100),
            Cooling VARCHAR(100),
            InternalUSB20 VARCHAR(100),
            FormFactor VARCHAR(100),
            NumberOfProcessorSockets VARCHAR(100),
            PCIslots VARCHAR(100),
            NumberOfHDMIOutputs VARCHAR(100),
            IPMI VARCHAR(100),
            SAS VARCHAR(100),
            EthernetConnection VARCHAR(100),
            Socket VARCHAR(100),
            HDMI VARCHAR(100),
            InternalParallelPort VARCHAR(100),
            TPM VARCHAR(100),
            NumberOf10100100010000MbitsPort VARCHAR(100),
            HeadphoneOutput VARCHAR(100),
            NetworkChip VARCHAR(100),
            TypeOfMemory VARCHAR(100),
            InternalUSB3031 VARCHAR(100),
            USB20 VARCHAR(100),
            eSATA VARCHAR(100),
            NumberOf101001000Mbitsports VARCHAR(100),
            mSATA VARCHAR(100),
            Bluetooth VARCHAR(100),
            Connections VARCHAR(100),
            ECCSupport VARCHAR(100),
            Firewire VARCHAR(100),
            PCIExpressx8 VARCHAR(100),
            TypeOfRAID VARCHAR(100),
            PCIExpressx1 VARCHAR(100),
            PCIExpressx4 VARCHAR(100),
            Graphicscard VARCHAR(100),
            ManufacturerWarranty VARCHAR(100),
            SCSIcontroller VARCHAR(100),
            PCIExpressVersion VARCHAR(100),
            SoundCard VARCHAR(100),
            PCIExpressx16 VARCHAR(100),
            MemorySpeeds VARCHAR(100),
            Manual VARCHAR(100),
            SATA15Gbs VARCHAR(100),
            USB31 VARCHAR(100),
            InternalUSB VARCHAR(100),
            ProductPage VARCHAR(200),
            ChassisFanConnectors VARCHAR(100),
            SPDIF VARCHAR(100),
            PCIExpressMini VARCHAR(100),
            BluetoothVersion VARCHAR(100),
            MemorySlots INT(2),
            MiniPCI VARCHAR(100),
            DVI VARCHAR(100),
            ComponentOutput VARCHAR(100),
            SupportForMultipleGraphicscards VARCHAR(100),
            IDEPATA VARCHAR(100),
            SupportForIntegratedGraphicsInCPU VARCHAR(100),
            AGPSlot VARCHAR(100),
            SATAExpress VARCHAR(100),
            MicrophoneInput VARCHAR(100),
            PS2 VARCHAR(100),
            NumberOfEthernetConnections VARCHAR(100),
            ParallelPort VARCHAR(100),
            NumberOfDisplayPortOutputs VARCHAR(100),
            NumberOf10100MbitsPorts VARCHAR(100),
            Chipset VARCHAR(100),
            Features VARCHAR(100),
            SerialPort VARCHAR(100),
            SATA3Gbs VARCHAR(100),
            MaximumAmountOfMemory VARCHAR(100),
            InternalUSB31 VARCHAR(100),
            DisplayPort VARCHAR(100),
            64bitProcessor VARCHAR(100),
            USB VARCHAR(100),
            SoundCardChip VARCHAR(100),
            DisplayPortVersion VARCHAR(100),
            RAIDController VARCHAR(100),
            USB3031 VARCHAR(100),
            Thunderbolt VARCHAR(100),
            CompatibleProcessors VARCHAR(100),
            HDMIVersion VARCHAR(100),
            U2 VARCHAR(100),
            Depth VARCHAR(100),
            ReleaseYear VARCHAR(100),
            InternalSPDIF VARCHAR(100),
            WirelessNetworkingStandard VARCHAR(100),
            TypeOfUSBConnector VARCHAR(100),
            M2 VARCHAR(100),
            PCIX VARCHAR(100),
            SATA VARCHAR(100),
            VGAOutputs VARCHAR(100),
            WirelessNetwork VARCHAR(100),
            SATA6Gbs VARCHAR(100),
            NumberOfDVIoutputs VARCHAR(100),
            CoaxialSPDIFout VARCHAR(100),
            PictBridge VARCHAR(100),
            GraphicsProcessor VARCHAR(100),
            MultiGPUTechnology VARCHAR(100),
            DVIHDMIAdapterIncluded VARCHAR(100),
            OpticalSPDIFout VARCHAR(100),
            NumberofThunderboltports VARCHAR(100),
            Firewireversion VARCHAR(100),
            Fibre VARCHAR(100),
			FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

        $sql->query("CREATE TABLE ODD(
            CompID INT (10)PRIMARY KEY NOT NULL,
            TypeOfDrive VARCHAR(100),
            Dimensions VARCHAR(100),
            AvailableColours VARCHAR(100),
            DVD VARCHAR(100),
            AccessTime INT(8),
            Platform VARCHAR(100),
            Location VARCHAR(100),
            LabellingTechnology VARCHAR(100),
            WriteSpeed INT(8),
            Bluray VARCHAR(100),
            CacheSize INT(8),
            SlotInTray VARCHAR(100),
            BurnsDVD VARCHAR(100),
            SupportsMDisc VARCHAR(100),
            Manual VARCHAR(100),
            CD VARCHAR(100),
            Connection VARCHAR(100),
            ProductPage VARCHAR(200),
            Weight INT(8),
            BurnsCD VARCHAR(100),
            ReadSpeed INT(8),
            BurnsBluray VARCHAR(100),
            FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

        $sql->query("CREATE TABLE AirCooler(
            CompID INT (10)PRIMARY KEY NOT NULL,
            Fancontrol VARCHAR(100),
            Airflow INT(8),
            Material VARCHAR(100),
            Dimensions VARCHAR(100),
            Weight INT(8),
            NumberOfFansIncluded INT(8),
            ThermalDesignPower INT(8),
            Noiselevel VARCHAR(100),
            ThermalResistance VARCHAR(100),
            Manual VARCHAR(100),
            LightingEffects VARCHAR(100),
            Fansize INT(8),
            ProductPage VARCHAR(200),
            HeatPipes INT(8),
            RotationalSpeed INT(8),
            ActiveCooling VARCHAR(100),
            Socket VARCHAR(100),
            No  VARCHAR(100),
            FanSupportforpassivecooler VARCHAR(100),
            Lightsource VARCHAR(100),
            Colour VARCHAR(100),
            FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

        $sql->query("CREATE TABLE WirelessAdapter(
            CompID INT (10)PRIMARY KEY NOT NULL,
            StandardsFollowed VARCHAR(100),
            DetachableAntenna VARCHAR(100),
            TotalDataTransferRate INT(8),
            Bluetoothversion DECIMAL(8,2),
            DataLinkLayer VARCHAR(100),
            Manual VARCHAR(100),
            24GHz VARCHAR(100),
            Bluetooth VARCHAR(100),
            Connection VARCHAR(100),
            ProductPage VARCHAR(200),
            ExternalAntenna VARCHAR(100),
            WirelessAecurity VARCHAR(100),
            DataTransferrate INT(8),
            WakeOnLAN VARCHAR(100),
            5GHz VARCHAR(100),
            Wirelesssecurity VARCHAR(100),
            FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

        $sql->query("CREATE TABLE WaterCooler(
            CompID INT (10)PRIMARY KEY NOT NULL,
            Socket VARCHAR(100),
            Waterblockincluded VARCHAR(100),
            Airflow INT(8),
            Placement VARCHAR(100),
            Dimensions VARCHAR(100),
            Weight INT(8),
            No VARCHAR(100),
            Noiselevel VARCHAR(100),
            Manual VARCHAR(100),
            Lightingeffects VARCHAR(100),
            Fansize INT(8),
            Productpage VARCHAR(200),
            Rotationalspeed INT(8),
            Activecooling VARCHAR(100),
            Features VARCHAR(100),
            FOREIGN KEY (CompID) REFERENCES Component(CompID) ON DELETE CASCADE);
        ");

        echo("Build complete");
        }catch(Exception $e) {
            echo 'Caught exception: ',  $e->getMessage(), "\n";
        }
?>
